// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxdRetXCg8dAh2ys9Bc3z8-ehc96b0WNo',
    appId: '1:242003220068:web:499090342b2e0e309cf171',
    messagingSenderId: '242003220068',
    projectId: 'fake-insta-d480d',
    authDomain: 'fake-insta-d480d.firebaseapp.com',
    storageBucket: 'fake-insta-d480d.firebasestorage.app',
    measurementId: 'G-DBQFWWYRM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ihsA2613kje6L1sl4GSYjwLAy1euH8w',
    appId: '1:242003220068:android:91c9581ba3a21e4c9cf171',
    messagingSenderId: '242003220068',
    projectId: 'fake-insta-d480d',
    storageBucket: 'fake-insta-d480d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz13QmalICxk038ZbPIaakpZJokF5jZMg',
    appId: '1:242003220068:ios:634c784019aef69a9cf171',
    messagingSenderId: '242003220068',
    projectId: 'fake-insta-d480d',
    storageBucket: 'fake-insta-d480d.firebasestorage.app',
    iosBundleId: 'com.example.fakeInstagram',
  );
}
